# Generated by Django 3.2.4 on 2021-07-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
