# Generated by Django 3.2.4 on 2021-07-14 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0007_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
