# Generated by Django 3.2.4 on 2021-07-20 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='is_active',
        ),
    ]
