# Generated by Django 3.2.4 on 2021-07-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0007_appuser_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name': 'username', 'verbose_name_plural': 'usernames'},
        ),
    ]
